name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    # Aquí está el cambio
    - name: Upload build artifact
      uses: actions/upload-artifact@v4 # Se actualizó de v3 a v4
      with:
        name: build-folder
        path: dist/ # Asegúrate de que esta sea la ruta correcta de tu carpeta de construcción
