name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    # Nuevo paso para subir los archivos generados como un artefacto
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: dist/ # Asegúrate de que esta sea la ruta correcta de tu carpeta de construcción
        
  deploy:
    needs: build # Este job solo se ejecutará si 'build' es exitoso
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-folder
      
      - name: Deploy to release/staging branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # La carpeta descargada será el directorio raíz
          publish_branch: release/staging
